[tool.poetry]
name = "langchain"
version = "0.1.0"
description = "study for ai"
authors = ["gitsilence"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
